version: "3.4"
services:
    react-nginx-app:
       stdin_open: true
       build:
         context: .
         dockerfile: Dockerfile
       expose:
         - 8000
       ports:
         - 8000:80
       environment:
         - CHOKIDAR_USEPOLLING=true
