export const SET_CITY = "SET_CITY";
export const SET_CURRENT_DATA = "SET_CURRENT_DATA";
export const SET_DAILY_DATA = "SET_DAILY_DATA";
export const SET_HOURLY_DATA = "SET_HOURLY_DATA";
export const SET_COORDINATES = "SET_COORDINATES";
export const SET_TIMEZONE_OFFSET = "SET_TIMEZONE_OFFSET";
export const CHANGE_TEMP_UNIT = "CHANGE_TEMP_UNIT";
export const TOGGLE_LOADING = "TOGGLE_LOADING";